;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-skip-close-maybe
        bison-electric-open-brace
        bison-electric-semicolon
        bison-indent-line
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        forward-sexp
        ignore
        indent-for-tab-command
        kill-region
        mark-sexp
        org-self-insert-command
        py-electric-delete
        ))

(setq mc/cmds-to-run-once
      '(
        describe-key
        keyboard-escape-quit
        lsp-ui-doc--handle-mouse-movement
        mouse-set-region
        ))
