---
- name: Sets additional groups for user {{ ansible_facts['env']['USER'] }}
  ansible.builtin.user:
    name: "{{ ansible_facts['env']['USER'] }}"
    append: true
    groups:
      - wheel
      - video
      - input
  become: true
  tags:
    - user
