---
- name: Helix
  tags:
    - helix
  block:
    - name: Symlink config
      ansible.builtin.file:
        src: "{{ role_path }}/files/config"
        dest: "{{ ansible_facts['user_dir'] }}/.config/helix"
        state: link
