# NOTE:
# Overrides /usr/share/sway/config.d/90-bar.conf


# Status Bar: waybar
#
# Read `man 5 sway-bar` for more information about this section.
# Read `man 5 waybar` for more information about the waybar instance style and layout configuration
#
# Requires: waybar

set $font Noto Sans 8
set $bar_font JetbrainsMono Nerd Font 8


##########################################################
## catpccin-mocha: https://github.com/catppuccin/i3/blob/main/themes/catppuccin-mocha
##########################################################

set $rosewater #f5e0dc
set $flamingo  #f2cdcd
set $pink      #f5c2e7
set $mauve     #cba6f7
set $red       #f38ba8
set $maroon    #eba0ac
set $peach     #fab387
set $green     #a6e3a1
set $teal      #94e2d5
set $sky       #89dceb
set $sapphire  #74c7ec
set $blue      #89b4fa
set $lavender  #b4befe
set $text      #cdd6f4
set $subtext1  #bac2de
set $subtext0  #a6adc8
set $overlay2  #9399b2
set $overlay1  #7f849c
set $overlay0  #6c7086
set $surface2  #585b70
set $surface1  #45475a
set $surface0  #313244
set $base      #1e1e2e
set $mantle    #181825
set $crust     #11111b

###########################################################
###########################################################

##########################################################
## catpccin-macchiato: https://github.com/catppuccin/i3/blob/main/themes/catppuccin-macchiato
##########################################################

set $rosewater #f4dbd6
set $flamingo #f0c6c6
set $pink #f5bde6
set $mauve #c6a0f6
set $red #ed8796
set $maroon #ee99a0
set $peach #f5a97f
set $yellow #eed49f
set $green #a6da95
set $teal #8bd5ca
set $sky #91d7e3
set $sapphire #7dc4e4
set $blue #8aadf4
set $lavender #b7bdf8
set $text #cad3f5
set $subtext1 #b8c0e0
set $subtext0 #a5adcb
set $overlay2 #939ab7
set $overlay1 #8087a2
set $overlay0 #6e738d
set $surface2 #5b6078
set $surface1 #494d64
set $surface0 #363a4f
set $base #24273a
set $mantle #1e2030
set $crust #181926


###########################################################
###########################################################


bar {
    swaybar_command swaybar
    status_command i3status

    font pango:JetBrains Mono NL 8


    separator_symbol "|"

    # Disable mouse wheel on the i3bar from switching workspaces.
    bindsym button4 nop
    bindsym button5 nop


    colors {
        background $crust
        statusline $text
        separator  $sapphire

        #                  Stroke color      Fill Color    Text Color
        focused_workspace  $surface0             $surface0         $text
        active_workspace   $surface0             $crust        $text
        inactive_workspace $crust            $crust        $text

        urgent_workspace   $crust            $red         $crust
        binding_mode       $maroon            $surface0         $maroon
    }

}

