exec noctalia

set $ipc noctalia msg

# Core binds
# bindsym $mod+space exec $ipc panel-toggle launcher
# bindsym $mod+s exec $ipc panel-toggle control-center
bindsym $mod+shift+v exec $ipc panel-toggle clipboard
# bindsym $mod+comma exec $ipc settings-toggle

# Media keys
bindsym --locked XF86AudioRaiseVolume exec $ipc volume-up
bindsym --locked XF86AudioLowerVolume exec $ipc volume-down
bindsym --locked XF86AudioMute exec $ipc volume-mute
bindsym --locked XF86MonBrightnessUp exec $ipc brightness-up
bindsym --locked XF86MonBrightnessDown exec $ipc brightness-down
