db_path = "~/.local/share/atuin/history.db"
key_path = "~/.local/share/atuin/key"

auto_sync = false
update_check = false

sync_address = "https://api.atuin.sh"


enter_accept = false

keymap_mode = "emacs"

[dotfiles]
enabled = false


[tmux]
enabled = true
width = "80%"
height = "60%"


[logs]
enabled = false

[theme]
name = "default"
debug = false

[ui]
syntax_highlight = true
