---
# TODO: https://github.com/eworm-de/mpd-notification

- name: Mpd
  tags:
    - mpd
    - mpc
    - ncmpcpp
    - never
  block:
    - name: Install
      ansible.builtin.dnf:
        name:
          - mpd
          - mpc
          - ncmpcpp
        state: present
      become: true

    - name: Install spotdl
      ansible.builtin.pip:
        name:
          - spotdl
        state: present
        version: 4.4.1


    - name: Create items
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ ansible_facts['user_dir'] }}/.cache/mpd"
        - "{{ ansible_facts['user_dir'] }}/.local/share/mpd/playlists"

    - name: Symlink config
      ansible.builtin.file:
        src: "{{ item }}"
        dest: "{{ ansible_facts['user_dir'] }}/.config/{{ item | basename }}"
        state: link
      loop:
        - "{{ role_path }}/files/mpd"
        - "{{ role_path }}/files/ncmpcpp"
