---
- name: TimeWarrior
  tags:
    - timewarrior
  block:
    - name: Install timewarrior
      ansible.builtin.dnf:
        name:
          - timew
        state: present
      become: true

    # - name: Symlink config
    #   ansible.builtin.file:
    #     src: "{{ role_path }}/files/taskrc"
    #     dest: "{{ ansible_facts['user_dir'] }}/.taskrc"
    #     state: link

