---
- name: TimeWarrior
  tags:
    - timewarrior
  block:
    - name: Install timewarrior
      ansible.builtin.dnf:
        name:
          - timew
        state: present
      become: true

    - name: Symlink config
      ansible.builtin.file:
        src: "{{ role_path }}/files/config"
        dest: "{{ ansible_facts['user_dir'] }}/.config/timewarrior"
        state: link


    - name: Check if TimeWarrior DB Directory exists
      ansible.builtin.stat:
        path: "{{ ansible_facts['user_dir'] }}/.local/share/timewarrior"
      register: timewarrior_db_dir

    # mkdir -p "$HOME/.local/share/dbus-1/services/"
    - name: "Create TimeWarrior DB Directory ({{ ansible_facts['user_dir'] }}/.local/share/timewarrior)"
      ansible.builtin.file:
        path: "{{ ansible_facts['user_dir'] }}/.local/share/timewarrior"
        state: directory
        mode: '0755'
        recurse: true
      when: not timewarrior_db_dir


      # Add hook for taskwarrior /usr/lib64/timew/ext/on-modify.timewarrior

    - name: Install taskwarrior hook for start/stop tracking
      ansible.builtin.copy:
        src: /usr/lib64/timew/ext/on-modify.timewarrior
        dest: "{{ ansible_facts['user_dir'] }}/.local/share/tasks/hooks/on-modify.timewarrior"
        mode: '0755'

