#!/usr/bin/env bash

set-option -g status-position bottom

# TokyoNight colors for Tmux

set -g mode-style "fg=#7aa2f7,bg=#3b4261"

set -g message-style "fg=#7aa2f7,bg=#3b4261"
set -g message-command-style "fg=#7aa2f7,bg=#3b4261"

set -g pane-border-style "fg=#3b4261"
set -g pane-active-border-style "fg=#7aa2f7"

set -g status "on"
set -g status-justify "left"

set -g status-style "fg=#7aa2f7,bg=#1f2335"

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE



# LEFT
set -g status-left "#[fg=#7aa2f7,bold]#S#[default] "

# RIGHT (12h)
set -g status-right "#[fg=#7aa2f7]#{prefix_highlight} #[fg=#a9b1d6]%Y-%m-%d | %I:%M %p #[fg=#7aa2f7]#h"

# RIGHT (24h override)
if-shell '[ "$(tmux show-option -gqv "clock-mode-style")" = "24" ]' {
  set -g status-right "#[fg=#7aa2f7]#{prefix_highlight} #[fg=#a9b1d6]%Y-%m-%d | %H:%M #[fg=#7aa2f7]#h"
}

# WINDOWS
setw -g window-status-separator " "

setw -g window-status-style "fg=#a9b1d6,bg=default"
setw -g window-status-current-style "fg=#7aa2f7,reverse,bold"

setw -g window-status-format "#I:#W"
setw -g window-status-current-format "#[bold]#I:#W"

# PREFIX HIGHLIGHT (simplified)
set -g @prefix_highlight_output_prefix "#[fg=#e0af68]("
set -g @prefix_highlight_output_suffix ")"

# Style for windows with activity (no bg change, orange fg)
setw -g window-status-activity-style "fg=#ff9e64,bg=default"

# Optional: bell (same idea)
setw -g window-status-bell-style "fg=#ff9e64,bg=default"
