config_version = 12

[bar.default]
background_opacity = 0.79999998211860657
capsule = true
capsule_thickness = 0.69999998807907104
center = []
end = [
    "media",
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "group:g1",
    "brightness",
    "battery",
    "session",
    "clock"
]
font_family = "JetBrainsMono Nerd Font Mono"
font_weight = 400
margin_ends = 0
position = "top"
start = [ "control-center", "launcher", "workspaces", "active_window" ]

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "input_volume", "volume" ]
    opacity = 1.0
    padding = 6.0

[calendar]
enabled = true

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
enabled = true
launcher_position = "start"
position = "right"
reserve_space = false
show_dots = true
smart_auto_hide = true

[hot_corners]
enabled = true

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[shell]
font_family = "JetBrainsMono Nerd Font"
panel_anchor_bar = "default"
polkit_agent = true

    [shell.panel]
    floating_layer = "top"

[theme]
builtin = "Tokyo-Night"
community_palette = "Tokyo Night Moon"
mode = "dark"
source = "builtin"
wallpaper_scheme = "vibrant"

    [theme.templates]
    builtin_ids = [ "sway" ]

[wallpaper]
enabled = false

    [wallpaper.default]
    path = "/usr/share/noctalia/assets/noctalia-wallpaper.png"

    [wallpaper.last]
    path = "/usr/share/noctalia/assets/noctalia-wallpaper.png"

[widget.active_window]
title_scroll = "on_hover"

[widget.control-center]
custom_image = "/usr/share/icons/hicolor/32x32/apps/fedora-logo-icon.png"
custom_image_colorize = true
icon_color = "primary"
