config_version = 13

[bar.default]
background_opacity = 0.79999998211860657
capsule = true
capsule_thickness = 0.69999998807907104
center = []
end = [
    "tray",
    "media",
    "clipboard",
    "group:g1",
    "group:g2",
    "bluetooth",
    "network",
    "brightness",
    "battery",
    "clock",
    "session",
    "notifications"
]
font_family = "JetBrainsMono Nerd Font Mono"
font_weight = 400
margin_ends = 0
position = "top"
start = [ "control-center", "launcher", "workspaces", "active_window" ]

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "input_volume", "volume" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g2"
    members = [ "ram", "cpu", "DISK" ]
    opacity = 1.0
    padding = 6.0


[calendar]
enabled = true

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
enabled = false
launcher_position = "start"
position = "right"
reserve_space = false
show_dots = true
smart_auto_hide = true

[hot_corners]
enabled = true

[location]
auto_locate = true

[lockscreen]
wallpaper = "/usr/share/backgrounds/gnome/adwaita-l.jxl"

[shell]
font_family = "JetBrainsMono Nerd Font"
panel_anchor_bar = "default"
polkit_agent = true

    [shell.panel]
    floating_layer = "top"

[theme]
builtin = "Tokyo-Night"
community_palette = "Tokyo Night Moon"
mode = "dark"
source = "builtin"
wallpaper_scheme = "vibrant"

    [theme.templates]
    builtin_ids = []

[wallpaper]
enabled = false

    [wallpaper.default]
    path = "/usr/share/noctalia/assets/noctalia-wallpaper.png"

    [wallpaper.last]
    path = "/usr/share/noctalia/assets/noctalia-wallpaper.png"

[widget.active_window]
title_scroll = "on_hover"

[widget.control-center]
custom_image = "/usr/share/icons/hicolor/32x32/apps/fedora-logo-icon.png"
custom_image_colorize = true
icon_color = "primary"

[widget.clock]
format = "{:%a  %Y-%m-%d  %H:%M}"

[widget.DISK]
type = "sysmon"
stat = "disk_free"
path = "/home"

[widget.media]
hide_when_no_media = true

